# Generated by Django 4.1.5 on 2023-12-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_favourite',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
